name: Build 数字报警 EXE


on:

  workflow_dispatch:



jobs:


  build-windows:


    runs-on: windows-latest


    steps:


    - name: 检出源码
      uses: actions/checkout@v4



    - name: 设置 Python

      uses: actions/setup-python@v5

      with:

        python-version: "3.11"



    - name: 升级 pip

      shell: cmd

      run: |

        python -m pip install --upgrade pip setuptools wheel



    # 安装 CPU Torch

    - name: 安装 CPU PyTorch

      shell: cmd

      run: |

        pip install ^
        --default-timeout=300 ^
        --retries=10 ^
        torch torchvision ^
        --index-url https://download.pytorch.org/whl/cpu



    # 安装依赖

    - name: 安装 requirements

      shell: cmd

      run: |

        pip install ^
        --default-timeout=300 ^
        --retries=10 ^
        -r requirements.txt



    # 检查文件

    - name: 检查工程

      shell: cmd

      run: |

        dir

        dir *.py

        dir *.spec

        dir *.ico



    # 打包

    - name: PyInstaller 打包

      shell: cmd

      run: |

        pyinstaller ^
        --clean ^
        --noconfirm ^
        ScreenAlarm.spec



    # 查看结果

    - name: 查看输出

      shell: cmd

      run: |

        dir dist



    # 上传

    - name: 上传数字报警

      uses: actions/upload-artifact@v4

      with:

        name: 数字报警-Windows

        path: dist/数字报警
